##server:
##  port: 31001
##spring:
##  application:
##     name: xc‐service‐manage‐cms
##
##  data:
##     mongodb:
##     uri:
##     mongodb://root:123@localhost:27017
##     database: xc_cms
#spring:
#  datasource:
#    name: mysql_test
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      filters: stat
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      #      url: jdbc:oracle:thin:@153.153.153.132:7070:orcl
#      url: jdbc:oracle:thin:@153.153.234.249:1521:orcl
#      #      url: jdbc:oracle:thin:@chuzj:1521:orcl
#      username: TY_WS
#      password: 123456
#      #     driver-class-name: com.mysql.jdbc.Driver
#      #     url: jdbc:mysql://localhost:3306/gasdep?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      #     username: root
#      #     password: 123456
#      initial-size: 1
#      min-idle: 2
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x' FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20